---
- name: Converge users role
  hosts: all
  gather_facts: false

  pre_tasks:
    - name: Install Python and required packages
      ansible.builtin.raw: apt-get update && apt-get install -y python3 sudo openssh-client
      changed_when: false

  roles:
    - role: users
