---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: users-role-ubuntu
    image: ubuntu:24.04
    pre_build_image: true
    privileged: true
    command: /bin/bash -c "while true; do sleep 10000; done"

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "${MOLECULE_PROJECT_DIRECTORY}/.."
  playbooks:
    converge: converge.yml
  inventory:
    group_vars:
      all:
        managed_users:
          - name: moleculeuser
            groups:
              - sudo
            ssh_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEOCNI+uy+9lUCH/oD74mpk+5YwY6gNa2BGqHHxYDFl/ molecule-test-key"
        managed_opt_directories:
          - path: /opt/moleculeuser_workdir
            owner: moleculeuser
            group: moleculeuser
            mode: "0660"

verifier:
  name: ansible
